name: Cache Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Prime cache-dfe2cdf
        id: prime-cache-dfe2cdf
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-dfe2cdf

      - name: Echo cache result
        run: |
          if [ "${{ steps.prime-cache-dfe2cdf.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit!"
          else
            echo "Cache miss"
          fi

      - name: Install dependencies
        run: npm install

