name: Daily Auto Commit

on:
  schedule:
    # Runs daily at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout for 23f2000294@ds.study.iitm.ac.in daily commit
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create or update commit file
      run: |
        echo "Automated daily commit for 23f2000294@ds.study.iitm.ac.in" > daily_log.txt
        date >> daily_log.txt
        
    - name: Configure git and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_log.txt
        git commit -m "Daily commit: $(date +'%Y-%m-%d %H:%M:%S') - 23f2000294@ds.study.iitm.ac.in"
        git push
